services:
  Edulog\DatatablesBundle\Controller\DatatablesController:
    arguments: ['@doctrine.orm.entity_manager', '@Edulog\DatatablesBundle\Service\DtFilterFactory']

  Edulog\DatatablesBundle\Service\DtFilterFactory:
    arguments: ['@session']

  # Extensions TWIG
  Edulog\DatatablesBundle\Twig\DatatableConfTwigExtension:
    arguments: ['@router']
    tags:
      - { name: twig.extension }